language: python

python:
  - "3.6"
  - "2.7"

install:
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install -e .

script:
  - pytest --cov=./vigilancemeteo

after_success:
  - codecov
